version: "3.1"

services:
        proxy:
                image: nginx:latest
                ports:
                        - "80:80"
                        - "443:443"
                volumes:
                        - ./proxy/nginx.conf:/etc/nginx/nginx.conf
                        - /var/log/nginx:/var/log/nginx #log파일의 위치
                        - /etc/letsencrypt:/etc/letsencrypt #letsencrypt 폴더 위치
                container_name: proxy
                depends_on:
                        - biscuit-react
                        - biscuit-service
                restart: always
                environment:
                        - TZ=Asia/Seoul

        mariadb:
                container_name: mariadb
                image: mariadb
                environment:
                        MYSQL_DATABASE: biscuit
                        MYSQL_USER: dev
                        MYSQL_PASSWORD: ssafy
                        MYSQL_ROOT_PASSWORD: chat6pt
                        TZ: Asia/Seoul
                command:
                        - --character-set-server=utf8mb4
                        - --collation-server=utf8mb4_unicode_ci 
                volumes:
                        - /var/lib/docker/volumes/mariadb/_data:/var/lib/mysql
                ports:
                        - "3306:3306"
                restart: always  

        biscuit-service:
                container_name: biscuit-service
                image: evekristin/biscuit-service:api
                expose:
                        - 8080
                depends_on:
                        - mariadb
                restart: always
                environment:
                        TZ: Asia/Seoul

        biscuit-react:
                container_name: biscuit-react
                image: evekristin/biscuit-react:front
                expose:
                        - 80
     
        jenkins:
                image: jenkins/jenkins
                privileged: true
                restart: always
                ports:
                        - "9090:8080"
                expose:
                        - 50000
                volumes:
                        - '/jenkins:/var/jenkins_home'
                        - '/var/run/docker.sock:/var/run/docker.sock'
                        - '/usr/bin/docker:/usr/bin/docker'
                environment:
                        TZ: "Asia/Seoul"
                user: root

        redis:
                container_name: redis 
                image: redis
                ports:
                        - "6379:6379"
                command: redis-server --requirepass chat6pt --port 6379
                hostname: biscuit

